title    Mace Linux install medium (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%MACE%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%MACE%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%MACEISO_UUID%
