title    Mace Linux install medium (%MACE%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%MACE%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%MACE%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%MACEISO_UUID% accessibility=on
